### ISSUE TITLE
Stacks not added correctly when using including/excluding from multiple indexes

### ISSUE THREAD

**Issue by groeges** [appsody/repo-tools#23]
Using a configuration file that generates a single consolidated index from multiple index which use include and exclude do not add the stacks to the consolidated index correctly.  Using an index like:
```
# File: example_repo_config.yaml
 # My organization stack hub
 name: My.org Stack Hub
 description: Test configuration to build 2 index files for the default and incubator repos.
 version: 0.1.0
 stacks:
   - name: default
     repos:
       - url: https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
         exclude:
           - kitura
           - node-red
           - python-flask
           - starter
           - swift
           - java-microprofile
           - nodejs
       - url: https://github.com/kabanero-io/collections/releases/download/0.6.0/kabanero-index.yaml
         include:
           - java-microprofile
 image-org:
 image-registry:
 nginx-image-name:
```
doesnt add the java-microprofile stack from the 2nd index file, but excludes it, as per the hub-build.sh output:
```
Config file: example_config/example_repo_config.yaml
  == Running pre_build.d scripts
  ==== Running prereq_check.sh
  == Done pre_build.d scripts
 Not retrieving or modifying any assets
 Creating consolidated index for default
 == fetching https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
 == Adding stacks from index https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
 ==== Adding stack nodejs-loopback 0.2.2
 ==== Excluding stack swift 0.2.5
 ==== Excluding stack node-red 0.1.1
 ==== Excluding stack python-flask 0.2.2
 ==== Excluding stack starter 0.1.2
 ==== Excluding stack java-microprofile 0.2.24
 ==== Adding stack java-spring-boot2 0.3.26
 ==== Excluding stack kitura 0.2.5
 ==== Adding stack java-openliberty 0.2.2
 ==== Excluding stack nodejs 0.3.4
 ==== Adding stack nodejs-express 0.4.3
 == fetching https://github.com/kabanero-io/collections/releases/download/0.6.0/kabanero-index.yaml
 == Adding stacks from index https://github.com/kabanero-io/collections/releases/download/0.6.0/kabanero-index.yaml
 ==== Excluding stack java-microprofile 0.2.25
 ==== Excluding stack java-openliberty 0.2.1
 ==== Excluding stack java-spring-boot2 0.3.23
 ==== Excluding stack nodejs-express 0.2.8
 ==== Excluding stack nodejs-loopback 0.1.8
 ==== Excluding stack nodejs 0.3.1
  == Running post_build.d scripts
  ==== Running build_nginx.sh
  == Done post_build.d scripts
```
